POST http://localhost:8080/api/admin/add
Content-Type: application/json

{
  "id": "",
  "name": "zsh",
  "password": "123",
  "authority": 0
}

###
POST http://localhost:8080/api/admin/update
token: c7e6f33821957cb98f9cc0ce108d14b69b8cc6f7e2adcbde48e7261dffb828531d84af1ab941d771aba6eb4e9e39ef0a
role: 6983f953b49c88210cb9
Content-Type: application/json

{
  "id": 11,
  "name": "del3",
  "password": "",
  "authority": 2

}
###
GET http://localhost:8080/api/admin/delete/5
Content-Type: application/json

###
GET http://localhost:8080/api/admin/select/zsh
Content-Type: application/json

//{
//  "name": "zsh"
//}
###
GET http://localhost:8080/api/admin/select_all
Content-Type: application/json

###

GET http://localhost:8080/api/admin/select_users
Content-Type: application/json

###