POST http://localhost:8080/api/admin/add
Content-Type: application/json

{
  "name": "qwe",
  "password": "123",
  "authority": 0
}

###
POST http://localhost:8080/api/admin/update
token: c7e6f33821957cb98f9cc0ce108d14b69b8cc6f7e2adcbde48e7261dffb828531d84af1ab941d771aba6eb4e9e39ef0a
role: 6983f953b49c88210cb9
Content-Type: application/json

{
  "id": 3,
  "name": "zsh",
  "password": "",
  "authority": 0

}
###
POST http://localhost:8080/api/admin/delete
Content-Type: application/json

{
  "id": 5
}
###
POST http://localhost:8080/api/admin/select
Content-Type: application/json

{
  "name": "zsh"
}
###
GET http://localhost:8080/api/admin/select_all
Content-Type: application/json

###