POST http://localhost:8080/api/3/bill/add
Content-Type: application/json

{
  "tables": {
    "id": 8
  },
  "menu": {
    "id": 2
  },
  "num": 1,
  "price": 5.32
}

###
GET http://localhost:8080/api/user2/getByStatue
Content-Type: application/json

###