POST http://localhost:8080/api/wechat/login
Content-Type: application/x-www-form-urlencoded

code=061xr7S91t3DgN1PBUQ91vK9S91xr7SI

###

POST http://localhost:8080/api/wechat/getUserInfo
token: d8a040674e66805348f39084c7b9de5a4bcd7e664708fdafc88eda391e7a6d27
Content-Type: application/x-www-form-urlencoded

code=祝世豪

###